site_name: Kyōkai (境界)
theme: cinder
repo_url: "https://github.com/SunDwarf/Kyokai"
copyright: "Kyōkai is licensed under the <a href='https://github.com/SunDwarf/Kyokai/blob/master/LICENCE'>MIT
license</a>"
pages:
  - Index: index.md
  - Examples:
      - Basic App: examples/first-app.md